
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.13/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell


wechat:
  mpAppId: wx0259d8f25f9cbfe0
  mpAppSecret: 3d3e2c40c217132d31642d473c7b80a3

wechatpay:
  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: H:/zfzs/h5.p12
  notifyUrl: http://hhwan.natapp1.cc/sell/pay/notify